name: Build and Deploy .NET 8 Blazor App to Azure App Service

on:
  workflow_dispatch:    

env:
  AZURE_WEBAPP_NAME: "romaanwebappone"
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore 

      - name: Publish
        run: dotnet publish -c Release -o ./publish

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME}}
          publish-profile: ${{ secrets.PUBLISH_SECRET }}
          package: ./publish

      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: 'https://romaanwebappone.azurewebsites.net/'
